#!/bin/bash

# Usage: ./,run-this-after-immich-go-archive-from-immich <folder>
#
# Problem: immich-go archive from-immich doesn't have file extensions
# - this means that immich-go upload command will not recognize the backed up assets properly.
# - for disaster recovery purposes
#

path=$1
find "$path" -type f ! -iname '*.json' | while read -r f; do
    filetype=$(file -b --mime-type "$f")

    # skip json files
    if [[ "$f" == *.json || "$f" == *.JSON ]]; then
        continue
    fi

    filename=$(basename "$f")

    # for those files with last character as "." in their filenames
    if [[ "$filename" == *"." ]]; then
        # just remove the trailing "." last character
        newname="${f%?}"
        mv "$f" "$newname"
        f="$newname"
        filename=$(basename "$f")
    fi

    # skip if has file extension already
    if [[ "$filename" == *.* ]]; then
        # echo "$f skipped: has file ext ($filename)"
        continue
    fi

    case $filetype in
    image/jpeg)
        mv "$f" "$f.jpg"
        ;;
    image/png)
        mv "$f" "$f.png"
        ;;
    # image/webp)
    #     # maybe parse the JSON metadata with jq -r '.fileName'
    #     # then extract file extension with cut -d. -f 2
    #     extracted_ft=$(jq -r '.fileName' "$f" | cut -d. -f 2)
    #     mv "$f" "$f.$extracted_ft"
    #     ;;
    image/gif)
        mv "$f" "$f.gif"
        ;;
    image/heic)
        mv "$f" "$f.heic"
        ;;
    video/mp4)
        mv "$f" "$f.mp4"
        ;;
    video/quicktime)
        mv "$f" "$f.mov"
        ;;
    # application/octet-stream)
    #     # maybe parse the JSON metadata with jq -r '.fileName'
    #     # then extract file extension with cut -d. -f 2
    #     extracted_ft=$(jq -r '.fileName' "$f" | cut -d. -f 2)
    #     mv "$f" "$f.$extracted_ft"
    #     ;;
    *)
        {
            echo "$f: Invalid filetype... will extract via its JSON file."
            # maybe parse the JSON metadata with jq -r '.fileName'
            # then extract file extension with cut -d. -f 2
            extracted_ft=$(jq -r '.fileName' "$f.JSON" | cut -d. -f 2)
            mv "$f" "$f.$extracted_ft"
        } || echo "Failed to extract via its JSON file."
        continue
        ;;
    esac
done

echo "[INFO] Done renaming files."
