#!/bin/bash

# this is the daily todo (daily quest)
# - creates new todolist with date (YYYY-MM-DD) as its filename
# - stores in vault/Personal/todos
# - requires "shortcuts/no-neck-pain.nvim" plugin to center the buffer

set -e

date_today=$(date +%Y-%m-%d)
todo_file="$VAULT/Personal/todos/"$date_today.md

# check if $VAULT path exists
cd "$VAULT" || {
    echo "No VAULT env path created. Set a VAULT path in your .zshrc or .bashrc first."
    exit 1
}

# if [ -z "$vault_check" ]; then
# 	echo "No VAULT env path created. Set a VAULT path in your .zshrc or .bashrc first."
# 	exit 1
# fi

new_todo() {
    touch "$todo_file"
    cat >"$todo_file" <<EOF
# DAILY QUEST for $date_today:

- [ ] Workout [if none, do trifecta (100 pushup, 100 situps, 100 squats)]
- [ ] system design and/or leetcode grind
- [ ] data-engineering (datacamp, zoomcamp, side projects)
    - zoomcamp
    - data-engineering-handbook
    - datacamp
    - leap bigquery
    - stdbadv

- [ ] **ITDBADM** proposal (DL: july 10)
- [ ] **ITNET01** case study (DL: july 14)

- [ ] spellbook-todos mini project
- [ ] learn dbt

## ACADS to complete this ILW

- [ ] PCK assessment for SAS2000 - dl on july 26
EOF
}

if [ ! -f "$todo_file" ]; then
    echo "[ NEW ] Creating $date_today.md..."
    new_todo
fi

if [[ "$*" == --nvim ]]; then
    nvim "$todo_file" -c ":NoNeckPain" '+ normal gg' # needs NoNeckPain nvim plugin (will still work if don't have it)
    # nvim '+ normal Gzzo' "$todo_file" -c :NoNeckPain
fi
